// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: voter/voter/query.proto

package voter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName        = "/voter.voter.Query/Params"
	Query_ShowPoll_FullMethodName      = "/voter.voter.Query/ShowPoll"
	Query_ShowPollVotes_FullMethodName = "/voter.voter.Query/ShowPollVotes"
	Query_ShowAllPolls_FullMethodName  = "/voter.voter.Query/ShowAllPolls"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ShowPoll items.
	ShowPoll(ctx context.Context, in *QueryShowPollRequest, opts ...grpc.CallOption) (*QueryShowPollResponse, error)
	// Queries a list of ShowPollVotes items.
	ShowPollVotes(ctx context.Context, in *QueryShowPollVotesRequest, opts ...grpc.CallOption) (*QueryShowPollVotesResponse, error)
	// Queries a list of ShowAllPolls items.
	ShowAllPolls(ctx context.Context, in *QueryShowAllPollsRequest, opts ...grpc.CallOption) (*QueryShowAllPollsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowPoll(ctx context.Context, in *QueryShowPollRequest, opts ...grpc.CallOption) (*QueryShowPollResponse, error) {
	out := new(QueryShowPollResponse)
	err := c.cc.Invoke(ctx, Query_ShowPoll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowPollVotes(ctx context.Context, in *QueryShowPollVotesRequest, opts ...grpc.CallOption) (*QueryShowPollVotesResponse, error) {
	out := new(QueryShowPollVotesResponse)
	err := c.cc.Invoke(ctx, Query_ShowPollVotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowAllPolls(ctx context.Context, in *QueryShowAllPollsRequest, opts ...grpc.CallOption) (*QueryShowAllPollsResponse, error) {
	out := new(QueryShowAllPollsResponse)
	err := c.cc.Invoke(ctx, Query_ShowAllPolls_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ShowPoll items.
	ShowPoll(context.Context, *QueryShowPollRequest) (*QueryShowPollResponse, error)
	// Queries a list of ShowPollVotes items.
	ShowPollVotes(context.Context, *QueryShowPollVotesRequest) (*QueryShowPollVotesResponse, error)
	// Queries a list of ShowAllPolls items.
	ShowAllPolls(context.Context, *QueryShowAllPollsRequest) (*QueryShowAllPollsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) ShowPoll(context.Context, *QueryShowPollRequest) (*QueryShowPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowPoll not implemented")
}
func (UnimplementedQueryServer) ShowPollVotes(context.Context, *QueryShowPollVotesRequest) (*QueryShowPollVotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowPollVotes not implemented")
}
func (UnimplementedQueryServer) ShowAllPolls(context.Context, *QueryShowAllPollsRequest) (*QueryShowAllPollsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAllPolls not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShowPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowPoll(ctx, req.(*QueryShowPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowPollVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowPollVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowPollVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShowPollVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowPollVotes(ctx, req.(*QueryShowPollVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowAllPolls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowAllPollsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowAllPolls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShowAllPolls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowAllPolls(ctx, req.(*QueryShowAllPollsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voter.voter.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowPoll",
			Handler:    _Query_ShowPoll_Handler,
		},
		{
			MethodName: "ShowPollVotes",
			Handler:    _Query_ShowPollVotes_Handler,
		},
		{
			MethodName: "ShowAllPolls",
			Handler:    _Query_ShowAllPolls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voter/voter/query.proto",
}
